# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Download\Python\AtividadeExtraclasseBD\Programa\Telas\TelaCadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(243, 232)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 180, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 40, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 47, 13))
        self.label_3.setObjectName("label_3")
        self.edtNome = QtWidgets.QLineEdit(Dialog)
        self.edtNome.setGeometry(QtCore.QRect(100, 30, 113, 20))
        self.edtNome.setObjectName("edtNome")
        self.edtPeso = QtWidgets.QLineEdit(Dialog)
        self.edtPeso.setGeometry(QtCore.QRect(100, 80, 113, 20))
        self.edtPeso.setObjectName("edtPeso")
        self.edtPreco = QtWidgets.QLineEdit(Dialog)
        self.edtPreco.setGeometry(QtCore.QRect(100, 130, 113, 20))
        self.edtPreco.setObjectName("edtPreco")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Nome:"))
        self.label_2.setText(_translate("Dialog", "Peso:"))
        self.label_3.setText(_translate("Dialog", "Preço:"))
