# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Qt Designer\DesignsFeitos\TelaCadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(243, 232)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 40, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 47, 13))
        self.label_3.setObjectName("label_3")
        self.edtNome = QtWidgets.QLineEdit(Dialog)
        self.edtNome.setGeometry(QtCore.QRect(100, 30, 113, 20))
        self.edtNome.setObjectName("edtNome")
        self.edtPeso = QtWidgets.QLineEdit(Dialog)
        self.edtPeso.setGeometry(QtCore.QRect(100, 80, 113, 20))
        self.edtPeso.setObjectName("edtPeso")
        self.edtPreco = QtWidgets.QLineEdit(Dialog)
        self.edtPreco.setGeometry(QtCore.QRect(100, 130, 113, 20))
        self.edtPreco.setObjectName("edtPreco")
        self.btnOk = QtWidgets.QPushButton(Dialog)
        self.btnOk.setGeometry(QtCore.QRect(20, 190, 75, 23))
        self.btnOk.setObjectName("btnOk")
        self.btnCancelar = QtWidgets.QPushButton(Dialog)
        self.btnCancelar.setGeometry(QtCore.QRect(140, 190, 75, 23))
        self.btnCancelar.setObjectName("btnCancelar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Nome:"))
        self.label_2.setText(_translate("Dialog", "Peso:"))
        self.label_3.setText(_translate("Dialog", "Preço:"))
        self.btnOk.setText(_translate("Dialog", "Ok"))
        self.btnCancelar.setText(_translate("Dialog", "Cancelar"))

class TelaCadastro(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Dialog()

        self.ui.setupUi(self)

        self.ui.btnOk      .clicked.connect(self.adiciona)
        self.ui.btnCancelar.clicked.connect(self.cancela )
    
    def adiciona(self):
        print("Adiciona clicado!")

    def cancela(self):
        print("Remove clicado!")
