# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Qt Designer\DesignsFeitos\TelaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(427, 676)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 150, 411, 481))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 311, 121))
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(220, 30, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.edtPesquisa = QtWidgets.QLineEdit(self.groupBox)
        self.edtPesquisa.setGeometry(QtCore.QRect(20, 30, 181, 21))
        self.edtPesquisa.setObjectName("edtPesquisa")
        self.btnPesquisar = QtWidgets.QPushButton(self.groupBox)
        self.btnPesquisar.setGeometry(QtCore.QRect(20, 90, 75, 23))
        self.btnPesquisar.setObjectName("btnPesquisar")
        self.btnAdicionar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdicionar.setGeometry(QtCore.QRect(340, 30, 75, 23))
        self.btnAdicionar.setObjectName("btnAdicionar")
        self.btnAtualizar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAtualizar.setGeometry(QtCore.QRect(340, 70, 75, 23))
        self.btnAtualizar.setObjectName("btnAtualizar")
        self.btnRemover = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemover.setGeometry(QtCore.QRect(340, 110, 75, 23))
        self.btnRemover.setObjectName("btnRemover")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 427, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Preço"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Peso"))
        self.groupBox.setTitle(_translate("MainWindow", "Pesquisar"))
        self.comboBox.setItemText(0, _translate("MainWindow", "ID"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Nome"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Preço"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Peso"))
        self.btnPesquisar.setText(_translate("MainWindow", "Pesquisar"))
        self.btnAdicionar.setText(_translate("MainWindow", "Adicionar"))
        self.btnAtualizar.setText(_translate("MainWindow", "Atualizar"))
        self.btnRemover.setText(_translate("MainWindow", "Remover"))
